Materials for reproducing Jakab (2018), *Competitor Scale and Mutual Fund Behavior*. If you have questions, contact the [author](laszlo.jakab@chicagobooth.edu). 

## Setup

Built under `R 3.4.3`. The following packages are used.
- `bookdown` (v. 0.7)
- `broom` (v. 0.4.3)
- `compsizer` (install using `devtools::install_github(laszlo-jakab/compsizer)`)
- `data.table` (v. 1.10.4-3)
- `doParallel` (v. 1.0.11)
- `foreach` (v. 1.4.4)
- `FredR` (install using `devtools::install_github("jcizel/FredR")`)
- `ggplot2` (v. 2.2.1)
- `gridExtra` (v. 2.3)
- `knitr` (v. 1.19)
- `laszlor` (install using `devtools::install_github("laszlo-jakab/laszlor")`)
- `lfe` (v. 2.6-2291)
- `lubridate` (v. 1.7.2)
- `magrittr` (v. 1.5)
- `rio` (v. 0.5.9)
- `rJava` (v. 0.9-9)
- `RJDBC` (v. 0.2-7)
- `xtable` (v. 1.8-2)
- `zoo` (v. 1.8-1)

Note that the `.Rprofile` file in the root loads `data.table` and `zoo`, as these packages are used throughout the project.

## Contents

### `R/`: Code

0. `Initialize_Folders.R`: Create folders for housing data and results.

1. `data_acquisition/`: Download data from the web.
    - `Pull_WRDS_Data.R`: Download data directly from WRDS using `R`'s interface.
    - `Other_Web_Data.R`: Download data from other sources on the web, such as active share, CPI, etc.

2. `data_wrangling/`: Prepare the data for analysis. Run in sequence.
    - `1-Clean.R`: Clean downloaded raw data.
    - `2-Benchmark_Returns.R`: Calculate factor-adjusted excess returns.
    - `3-Portfolio_Weights.R`: Calculate fund portfolio weights.
    - `4-Identify_Active_Funds.R`: Implement filters for identifying actively managed domestic equity funds.
    - `5-CompetitorSize.R`: Calculate *CompetitorSize* measure
    - `6-Dln_CompetitorSize.R`: Calculate quarter-end-to-quarter-end changes in log *CompetitorSize*, holding fund similarity constant.
    - `7-Portfolio_Liquidity.R`: Calculate portfolio liquidity and its sub-components.
    - `8-Portfolio_Groups.R`: Group funds into ten groups based on k-means clustering of portfolio weights.
    - `9-Combine_Data.R`: Combine dataset.
    - `scandal/`: Prepare the dataset used in the scandal analysis.
        - `1-ScandalExposure.R`: Calculate *ScandalExposure*.
        - `2-ScandalOutFlow.R`: Calculate *ScandalOutFlow*.
        - `3-Scandal_Analysis_Data.R` Combine dataset used in scandal analysis.

### `data/`: Data used in analysis

- `scandal/scandal_wficns_2018-Mar-06.Rds`: File containing categorization of funds by scandal status. Categorization done manually; this is the only piece of data generated outside of the code in the `R/` folder.  

### `thesis/`: Files to generate dissertation pdf.

- `render_book.R`: Compiles the document.
- `preamble.tex`: Additional tex in the preamble.
- `index.Rmd`: Front matter.
- `01-intro.Rmd`-`07-conclusion.Rmd`: Main body.
- `appendix-01-summary.Rmd`-`appendix-04-scandal.Rmd`: Appendices.
- `ref-toc.Rmd`: Make sure references show up in toc.
- `mf-references.bib`: Bibliography file.
- `_bookdown.yml`, `_output.yml`: Options for rendering the document.
- `ucetd.cls`: Latex class file to conform to UofC formatting requirements. 

### `packrat`

Files generated by `packrat` for package management.
