# Additional Results: Mutual Fund Scandal

```{r, include = FALSE}
# Setup ------------------------------------------------------------------------

# packages
pkgs <- c(
  "data.table",
  "zoo",
  "knitr",
  "xtable"
)
lapply(pkgs, library, character.only = TRUE)
options(knitr.kable.NA = '')

# quiet xtable
options(xtable.comment = FALSE)

# directories
setwd("..")

# load tables
reg.scandal <- readRDS("tab/reg_scandal.Rds")
tab.scandal <- readRDS("tab/summary_stats_scandal.Rds")
# ------------------------------------------------------------------------------
```


```{r snapShot200308, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
# Summary by Scandal Status ----------------------------------------------------

# number of columns
nc <- ncol(tab.scandal$by.scandal$results)
# add caption and panel headers
add.to.row <- list(pos = list(-1), command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  tab.scandal$by.scandal$caption, "}\\\\\n \\addlinespace"))
add.to.row$command <- command

# convert table to latex
print(
  xtable(tab.scandal$by.scandal$results,
    align = paste(c("ll", rep("Z", (nc - 1))), collapse = ""),
    caption = tab.scandal$by.scandal$title,
    label = "tab:snapShot200308",
    display = c("s", rep("f", nc)),
    digits = 2
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    caption.placement = 'top',
    format.args = list(big.mark = ",", drop0trailing = TRUE),
    include.rownames = FALSE
    )
# ------------------------------------------------------------------------------
```


```{r snapShotHL200308, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
# Summary by Scandal Exposure ----------------------------------------------------

# number of columns
nc <- ncol(tab.scandal$by.exposure$results)
# add caption and panel headers
add.to.row <- list(pos = list(-1), command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  tab.scandal$exposure$caption, "}\\\\\n \\addlinespace"))
add.to.row$command <- command

# convert table to latex
print(
  xtable(tab.scandal$by.exposure$results,
    align = paste(c("ll", rep("Z", (nc - 1))), collapse = ""),
    caption = tab.scandal$by.exposure$title,
    label = "tab:snapShotHL200308",
    display = c("s", rep("f", nc)),
    digits = 2
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    caption.placement = 'top',
    format.args = list(big.mark = ",", drop0trailing = TRUE),
    include.rownames = FALSE
    )
# ------------------------------------------------------------------------------
```



```{r scandalSpilloverPreTrend, echo = FALSE, warning = FALSE, message = FALSE, results = 'asis'}
# DiD Pre-Trend ----------------------------------------------------------------

# label columns
setnames(reg.scandal$pt$results, 
  c("Dep. Var.:", "$\\ln(C.S.)$", "$\\ln(AS)$",
    "$\\ln(TL^{-1/2})$", "$\\ln(L)$", "$\\ln(S)$",
    "$\\ln(D)$", "$\\ln(C)$", "$\\ln(B)$"))

# add caption and panel headers
rb <- nrow(reg.scandal$pt$sub.results$w1yr)
nc <- ncol(reg.scandal$pt$results)
add.to.row <- list(
  pos = list(-1, 0, 0, rb, rb, rb), 
  command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  reg.scandal$pt$caption, "}\\\\\n\\addlinespace"),
  # 0
  "\\midrule \\\\\n",
  # 0
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel A: 1 year window}}\\\\\n"),
  # Panel B
  "\\midrule \\\\\n",
  # Panel B
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel B: 2 year window}} \\\\\n"),
  # Panel B
  "\\midrule ")
add.to.row$command <- command

# print the table
print(
  xtable(reg.scandal$pt$results,
    align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
    caption = reg.scandal$pt$title,
    label = "tab:scandalSpilloverPreTrend"
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames = FALSE,
    caption.placement = 'top'
    )
# ------------------------------------------------------------------------------
```


```{r scandalSpilloverMXBim, echo = FALSE, warning = FALSE, message = FALSE, results = 'asis'}
# DiD, Bm X Date FE ------------------------------------------------------------

# label columns
setnames(reg.scandal$did.bm$results, 
  c("Dep. Var.:", "$\\ln(C.S.)$", "$\\ln(AS)$",
    "$\\ln(TL^{-1/2})$", "$\\ln(L)$", "$\\ln(S)$",
    "$\\ln(D)$", "$\\ln(C)$", "$\\ln(B)$"))

# add caption and panel headers
rb <- nrow(reg.scandal$did.bm$sub.results$w1yr)
nc <- ncol(reg.scandal$did.bm$results)
add.to.row <- list(pos = list(-1, 0, 0, rb, rb, rb), command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  reg.scandal$did.bm$caption, "}\\\\\n\\addlinespace"),
  # 0
  "\\midrule \\\\\n",
  # 0
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel A: 1 year window}}\\\\\n"),
  # Panel B
  "\\midrule \\\\\n",
  # Panel B
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel B: 2 year window}} \\\\\n"),
  # Panel B
  "\\midrule ")
add.to.row$command <- command

# print the table
print(
  xtable(reg.scandal$did.bm$results,
    align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
    caption = reg.scandal$did.bm$title,
    label = "tab:scandalSpilloverMXBim"
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames = FALSE,
    caption.placement = 'top'
    )
# ------------------------------------------------------------------------------
```


```{r scandalSpilloverPreTrendMXBim, echo = FALSE, warning = FALSE, message = FALSE, results = 'asis'}
# Pre-Trend, Bm X Date FE ------------------------------------------------------

# label columns
setnames(reg.scandal$pt.bm$results, 
  c("Dep. Var.:", "$\\ln(C.S.)$", "$\\ln(AS)$",
    "$\\ln(TL^{-1/2})$", "$\\ln(L)$", "$\\ln(S)$",
    "$\\ln(D)$", "$\\ln(C)$", "$\\ln(B)$"))

# add caption and panel headers
rb <- nrow(reg.scandal$pt.bm$sub.results$w1yr)
nc <- ncol(reg.scandal$pt.bm$results)
add.to.row <- list(pos = list(-1, 0, 0, rb, rb, rb), command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  reg.scandal$pt.bm$caption, "}\\\\\n\\addlinespace"),
  # 0
  "\\midrule \\\\\n",
  # 0
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel A: 1 year window}}\\\\\n"),
  # Panel B
  "\\midrule \\\\\n",
  # Panel B
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel B: 2 year window}} \\\\\n"),
  # Panel B
  "\\midrule "
  )
add.to.row$command <- command

# print the table
print(
  xtable(reg.scandal$pt.bm$results,
    align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
    caption = reg.scandal$pt.bm$title,
    label = "tab:scandalSpilloverPreTrendMXBim"
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames = FALSE,
    caption.placement = 'top'
    )
# ------------------------------------------------------------------------------
```


```{r scandalSpilloverIVMXBim, echo = FALSE, warning = FALSE, message = FALSE, results = 'asis'}
# ScandalOutFlow, Bm X Date FE -------------------------------------------------

# label columns
setnames(reg.scandal$sof.bm$results, 
  c("Dep. Var.:", "$\\ln(C.S.)$", "$\\ln(AS)$",
    "$\\ln(TL^{-1/2})$", "$\\ln(L)$", "$\\ln(S)$",
    "$\\ln(D)$", "$\\ln(C)$", "$\\ln(B)$"))

# add caption and panel headers
rb <- nrow(reg.scandal$sof.bm$sub.results$w1yr)
nc <- ncol(reg.scandal$sof.bm$results)
add.to.row <- list(pos = list(-1, 0, 0, rb, rb, rb), command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  reg.scandal$sof.bm$caption, "}\\\\\n\\addlinespace"),
  # 0
  "\\midrule \\\\\n",
  # 0
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel A: 1 year window}}\\\\\n"),
  # Panel B
  "\\midrule \\\\\n",
  # Panel B
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel B: 2 year window}} \\\\\n"),
  # Panel B
  "\\midrule ")
add.to.row$command <- command

# print the table
print(
  xtable(reg.scandal$sof.bm$results,
    align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
    caption = reg.scandal$sof.bm$title,
    label = "tab:scandalSpilloverIVMXBim"
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames = FALSE,
    caption.placement = 'top'
    )
# ------------------------------------------------------------------------------
```


```{r scandal2SLS, echo = FALSE, warning = FALSE, message = FALSE, results = 'asis'}
# 2SLS -------------------------------------------------------------------------

# label columns
setnames(reg.scandal$iv$results, 
  c("Dep. Var.:", "$\\ln(AS)$", "$\\ln(TL^{-1/2})$", "$\\ln(L)$", 
    "$\\ln(S)$", "$\\ln(D)$", "$\\ln(C)$", "$\\ln(B)$"))

# add caption and panel headers
rb <- nrow(reg.scandal$iv$sub.results$w1yr)
nc <- ncol(reg.scandal$iv$results)
add.to.row <- list(pos = list(-1, 0, 0, rb, rb, rb), command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  reg.scandal$iv$caption, "}\\\\\n\\addlinespace"),
  # 0
  "\\midrule \\\\\n",
  # 0
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel A: 1 year window}}\\\\\n"),
  # Panel B
  "\\midrule \\\\\n",
  # Panel B
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel B: 2 year window}} \\\\\n"),
  # Panel B
  "\\midrule ")
add.to.row$command <- command

# print the table
print(
  xtable(reg.scandal$iv$results,
    align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
    caption = reg.scandal$iv$title,
    label = "tab:scandal2SLS"
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames = FALSE,
    caption.placement = 'top'
    )
# ------------------------------------------------------------------------------
```


```{r scandal2SLSmXbim, echo = FALSE, warning = FALSE, message = FALSE, results = 'asis'}
# 2SLS, Bm X Date FE -----------------------------------------------------------

# label columns
setnames(reg.scandal$iv.bm$results, 
  c("Dep. Var.:", "$\\ln(AS)$", "$\\ln(TL^{-1/2})$", "$\\ln(L)$", 
    "$\\ln(S)$", "$\\ln(D)$", "$\\ln(C)$", "$\\ln(B)$"))

# add caption and panel headers
rb <- nrow(reg.scandal$iv.bm$sub.results$w1yr)
nc <- ncol(reg.scandal$iv.bm$results)
add.to.row <- list(pos = list(-1, 0, 0, rb, rb, rb), command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  reg.scandal$iv.bm$caption, "}\\\\\n\\addlinespace"),
  # 0
  "\\midrule \\\\\n",
  # 0
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel A: 1 year window}}\\\\\n"),
  # Panel B
  "\\midrule \\\\\n",
  # Panel B
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel B: 2 year window}} \\\\\n"),
  # Panel B
  "\\midrule ")
add.to.row$command <- command

# print the table
print(
  xtable(reg.scandal$iv.bm$results,
    align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
    caption = reg.scandal$iv.bm$title,
    label = "tab:scandal2SLSmXbim"
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames = FALSE,
    caption.placement = 'top'
    )
# ------------------------------------------------------------------------------
```
