# (APPENDIX) Appendix {-}

# Summary Statistics

```{r, include = FALSE}
# Setup ------------------------------------------------------------------------

# packages
pkgs <- c(
  "data.table",
  "zoo",
  "knitr",
  "kableExtra",
  "ggplot2",
  "gridExtra"
)
lapply(pkgs, library, character.only = TRUE)
options(knitr.kable.NA = '')

# output format
#out.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
options(knitr.table.format = "html")

# directories
setwd("..")

# load tables
summary.tab <- readRDS("tab/summary_stats.Rds")

# load figures
summary.fig <- readRDS("fig/summary_plots.Rds")

# custom colors
azure <- "#007FFF"
orangebrown <- "#E67300"
lgreen <- "#00eb76"

# -----------------------------------------------------------------------------
```


## Tables


```{r sumStats, echo = FALSE, message = FALSE, digits = 2, format.args = list(big.mark = ",")}
# Summary Statistics -----------------------------------------------------------

summary.tab$summary.stats$results %>%
  kable(type = "html", digits = 2, format.args = list(big.mark = ","),
    caption = summary.tab$summary.stats$title) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover"), 
    position = "center",
    font_size = 11) %>%
  group_rows("Panel A: Fund level means", 
    1, dim(summary.tab$summary.stats$sub.results$fund.level)[1], 
    label_row_css = "text-align: center;") %>%
  group_rows("Panel B: Fund-month level statistics", 
    dim(summary.tab$summary.stats$sub.results$fund.level)[1]+1, 
    dim(summary.tab$summary.stats$results)[1], 
    label_row_css = "text-align: center;") %>%
  footnote(summary.tab$summary.stats$caption)

# ------------------------------------------------------------------------------
```


```{r correlations, echo = FALSE, message = FALSE, warning = FALSE}
# Correlations -----------------------------------------------------------------
summary.tab$correlations$results %>%
  kable(type = "html",
        digits = 2, 
        caption = summary.tab$correlations$title) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover"), 
    position = "center",
    font_size = 11) %>%
  group_rows("Panel A: Unconditional Correlations", 
    1, dim(summary.tab$correlations$sub.results$unconditional)[1], 
    label_row_css = "text-align: center;") %>%
  group_rows("Panel B: Within-Fund Correlations", 
    dim(summary.tab$correlations$sub.results$unconditional)[1]+1, 
    dim(summary.tab$correlations$results)[1], 
    label_row_css = "text-align: center;") %>%
  footnote(summary.tab$correlations$caption)
# ------------------------------------------------------------------------------
```


## Figures


```{r sampleCompleteness, echo = FALSE, dpi = 300, fig.width = 6, fig.height = 7, fig.cap = paste(summary.fig$crsp$title, summary.fig$crsp$caption)}
# Data Availability in CRSP ----------------------------------------------------
grid.arrange(
  summary.fig$crsp$results$mret,
  summary.fig$crsp$results$mtna,
  summary.fig$crsp$results$exp_ratio, 
  nrow = 3)
# -----------------------------------------------------------------------------
```


```{r rdateFreq, echo = FALSE, dpi = 300, fig.width = 6, fig.height = 4, fig.cap = paste(summary.fig$rdates$title, summary.fig$rdates$caption)}
# Report Dates in Thomson ------------------------------------------------------
summary.fig$rdates$results
# -------------------------------------------------------------------------------
```


```{r industrySize, echo=FALSE, dpi = 300, fig.width = 6, fig.height = 3, fig.cap = paste(summary.fig$industry$title, summary.fig$industry$caption)}
# Industry Size Time Series Plot -----------------------------------------------
summary.fig$industry$results
# ------------------------------------------------------------------------------
```
