# Additional Results: Capital Allocation

```{r, include = FALSE}
# Setup ------------------------------------------------------------------------

# packages
pkgs <- c(
  "data.table",
  "zoo",
  "knitr",
  "xtable"
)
lapply(pkgs, library, character.only = TRUE)
options(knitr.kable.NA = '')

# quiet xtable
options(xtable.comment = FALSE)

# directories
setwd("..")

# load tables
reg.behavior <- readRDS("tab/reg_behavior.Rds")

# ----------------------------------------------------------------------
```


```{r fundResponseMXBim, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'} 

# label columns
setnames(reg.behavior$bd$results, 
  c("Dep. Var.:", "$\\Delta\\ln(AS)$", "$\\Delta\\ln(TL^{-1/2})$",
    "$\\Delta\\ln(L)$", "$\\Delta\\ln(S)$", "$\\Delta\\ln(D)$", 
    "$\\Delta\\ln(C)$", "$\\Delta\\ln(B)$"))

# add caption to top of table
add.to.row <- list(pos = list(-1), command = NULL)
command <-
  paste0(
    "\\multicolumn{", ncol(reg.behavior$bd$results), 
    "}{p{.975\\textwidth}}{\\scriptsize ",
    reg.behavior$bd$caption, "} \\\\ \\addlinespace")
add.to.row$command <- command

# print the table
print(
  xtable(reg.behavior$bd$results,
    align = paste(c("ll", rep("Y", (ncol(reg.behavior$bd$results) - 1))), collapse = ""),
    caption = reg.behavior$bd$title,
    label = "tab:fundResponseMXBim"),
    sanitize.text.function=function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames=FALSE,
    caption.placement = 'top'
    )

# --------------------------------------------------------------------------------
```


```{r fundResponse08, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'} 

# label columns
setnames(reg.behavior$baseline.08$results, 
  c("Dep. Var.:", "$\\Delta\\ln(AS)$", "$\\Delta\\ln(TL^{-1/2})$",
    "$\\Delta\\ln(L)$", "$\\Delta\\ln(S)$", "$\\Delta\\ln(D)$", 
    "$\\Delta\\ln(C)$", "$\\Delta\\ln(B)$"))

# add caption to top of table
add.to.row <- list(pos = list(-1), command = NULL)
command <-
  paste0(
    "\\multicolumn{", ncol(reg.behavior$baseline.08$results), 
    "}{p{.975\\textwidth}}{\\scriptsize ",
    reg.behavior$baseline.08$caption, "} \\\\ \\addlinespace")
add.to.row$command <- command

# print the table
print(
  xtable(reg.behavior$baseline.08$results,
    align = paste(c("ll", rep("Y", (ncol(reg.behavior$baseline.08$results) - 1))), collapse = ""),
    caption = reg.behavior$baseline.08$title,
    label = "tab:fundResponse08"),
    sanitize.text.function=function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames=FALSE,
    caption.placement = 'top'
    )

# --------------------------------------------------------------------------------
```


```{r fundResponseMXBim08, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'} 

# label columns
setnames(reg.behavior$bd.08$results, 
  c("Dep. Var.:", "$\\Delta\\ln(AS)$", "$\\Delta\\ln(TL^{-1/2})$",
    "$\\Delta\\ln(L)$", "$\\Delta\\ln(S)$", "$\\Delta\\ln(D)$", 
    "$\\Delta\\ln(C)$", "$\\Delta\\ln(B)$"))

# add caption to top of table
add.to.row <- list(pos = list(-1), command = NULL)
command <-
  paste0(
    "\\multicolumn{", ncol(reg.behavior$bd.08$results), 
    "}{p{.975\\textwidth}}{\\scriptsize ",
    reg.behavior$bd$caption, "} \\\\ \\addlinespace")
add.to.row$command <- command

# print the table
print(
  xtable(reg.behavior$bd.08$results,
    align = paste(c("ll", rep("Y", (ncol(reg.behavior$bd.08$results) - 1))), collapse = ""),
    caption = reg.behavior$bd.08$title,
    label = "tab:fundResponseMXBim08"),
    sanitize.text.function=function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames=FALSE,
    caption.placement = 'top'
    )

# --------------------------------------------------------------------------------
```

