# (APPENDIX) Appendix {-}

\singlespacing

# Summary Statistics

```{r, include = FALSE}
# Setup ------------------------------------------------------------------------

# packages
pkgs <- c(
  "data.table",
  "zoo",
  "knitr",
  "xtable",
  "ggplot2",
  "gridExtra"
)
lapply(pkgs, library, character.only = TRUE)
options(knitr.kable.NA = '')

# quiet xtable
options(xtable.comment = FALSE)

# macros for labeling tables
mr <- "\\midrule"
mrn <- "\\midrule \\\\\n"
TCap <- function(nc, txt) {
  paste0("\\multicolumn{", nc, "}{p{.975\\textwidth}}{", txt, "}",
    " \\\\\n \\addlinespace")
}

# directories
setwd("..")

# load tables
summary.tab <- readRDS("tab/summary_stats.Rds")

# load figures
summary.fig <- readRDS("fig/summary_plots.Rds")

# custom colors
azure <- "#007FFF"
orangebrown <- "#E67300"
lgreen <- "#00eb76"

# -----------------------------------------------------------------------------
```


## Tables


```{r sumStats, echo = FALSE, message = FALSE, results = 'asis'}
# Summary Statistics -----------------------------------------------------------

# add caption and panel headers
rb <- nrow(summary.tab$summary.stats$sub.results$fund.level)
nc <- ncol(summary.tab$summary.stats$results)
# add caption and panel headers
add.to.row <- list(
  pos = list(-1, 0, 0, rb, rb, rb), 
  command = NULL)
command <- c(
  # -1
  paste0(
    "\\multicolumn{", (nc + 1), "}{p{.975\\textwidth}}{",
	  summary.tab$summary.stats$caption, "}\\\\\n\\addlinespace"),
  # 0
  "\\midrule \\\\\n",
  # 0
  paste0(
    "\\multicolumn{", nc, "}{c}{\\textbf{Panel A: Fund level means}}\\\\\n"),
  # Panel B
  "\\midrule \\\\\n",
  # Panel B
  paste0(
    "\\multicolumn{", nc, "}{c}{\\textbf{Panel B: Fund-month level statistics}} \\\\\n"),
  # Panel B
  "\\midrule "
  )
add.to.row$command <- command

# convert table to latex
out.tab <- print.xtable(
  xtable(summary.tab$summary.stats$results,
    caption = summary.tab$summary.stats$title,
    label = "tab:sumStats",
    display = c("s", "d", rep("f", (ncol(summary.tab$summary.stats$results) - 1)))
    ),
    format.args = list(big.mark = ",", drop0trailing = TRUE),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    caption.placement = 'top',
    print.results = FALSE
    )
# fix alignment
out.tab <- gsub("rrrrrrrrrrr", "@{}lrYYYYYYYYY@{}", out.tab, fixed = TRUE)

# print table
cat(out.tab)

# ------------------------------------------------------------------------------
```



```{r correlations, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
# Correlations -----------------------------------------------------------------

# add caption and panel headers
rb <- nrow(summary.tab$correlations$sub.results$unconditional)
nc <- ncol(summary.tab$correlations$results)
# add caption and panel headers
add.to.row <- list(
  pos = list(-1, 0, 0, rb, rb, rb), 
  command = NULL)
command <- c(
  # -1
  TCap(nc, summary.tab$correlations$caption)
  paste0(
    "\\multicolumn{", nc, "}{p{.975\\textwidth}}{",
	  summary.tab$correlations$caption, "}\\\\\n\\addlinespace"),
  # 0
  paste0("\\midrule \\multicolumn{", nc, "}{c}{} \\\\\n"),
  # 0
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel A: Unconditional}}\\\\\n"),
  # Panel B
  paste0("\\midrule \\multicolumn{", nc, "}{c}{} \\\\\n"),
  # Panel B
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{Panel B: Within-fund correlations}} \\\\\n"),
  # Panel B
  "\\midrule "
  )
add.to.row$command <- command

# convert table to latex
print(
  xtable(summary.tab$correlations$results,
    align = paste(c("ll|", rep("Z", (nc - 1))), collapse = ""),
    caption = summary.tab$correlations$title,
    label = "tab:correlations",
    display = c("s", rep("f", nc)),
    digits = 2
    ),
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    caption.placement = 'top',
    include.rownames = FALSE
    )

# ------------------------------------------------------------------------------
```




## Figures


```{r sampleCompleteness, echo = FALSE, dpi = 300, fig.width = 6, fig.height = 7, fig.cap = paste(summary.fig$crsp$title, summary.fig$crsp$caption)}
# Data Availability in CRSP ----------------------------------------------------
grid.arrange(
  summary.fig$crsp$results$mret,
  summary.fig$crsp$results$mtna,
  summary.fig$crsp$results$exp_ratio, 
  nrow = 3)
# -----------------------------------------------------------------------------
```


```{r rdateFreq, echo = FALSE, dpi = 300, fig.width = 6, fig.height = 3, fig.cap = paste(summary.fig$rdates$title, summary.fig$rdates$caption)}
# Report Dates in Thomson ------------------------------------------------------
summary.fig$rdates$results
# -------------------------------------------------------------------------------
```


```{r industrySize, echo=FALSE, dpi = 300, fig.width = 6, fig.height = 3, fig.cap = paste(summary.fig$industry$title, summary.fig$industry$caption)}
# Industry Size Time Series Plot -----------------------------------------------
summary.fig$industry$results
# ------------------------------------------------------------------------------
```
