\mainmatter
\chapter{Introduction}

```{r, include = FALSE}
# Setup ------------------------------------------------------------------------

# packages
pkgs <- c(
  "data.table",
  "zoo",
  "knitr")
lapply(pkgs, library, character.only = TRUE)

setwd("..")

# load data
combined <- readRDS("data/combined/combined.Rds")
# ------------------------------------------------------------------------
```


What is the impact of competition on the investment decisions of active mutual funds? Competition affects both a fund's efficient scale and the optimal composition of its investments. Outside investors allocate capital to the fund based on its perceived ability to generate risk adjusted returns. Fund managers allocate capital across available investment opportunities, taking the size of the fund as given. There is a key tension when mutual funds face decreasing returns to scale. As competition eliminates investment opportunities, the fund's optimal response is to reallocate capital toward passive portfolios. However, if investors are symmetrically informed, they withdraw capital from the fund [@bg04]. Decreased fund size lowers the marginal cost of active management, countervailing the shift toward passivity. Models of fund behavior predict the size effect to dominate in equilibrium, implying increased capital allocated to active strategies in response to competition [@pst17L].

I exploit changes in the size of competing funds to identify the effect of competition on funds' capital allocation. I demonstrate that funds respond to competition by reallocating capital from costly active strategies to cheaper, more passive portfolios. I address endogeneity concerns by investigating a natural experiment created by the 2003 mutual fund scandal. Fund families engulfed by the scandal were penalized by investor outflows, which I exploit as quasi-exogenous variation in competitor size. I show that close competitors of affected funds increased active management, and reaped improved performance following the scandal.

Interpreting my findings through models of fund behavior featuring decreasing returns to scale [@bg04; pst17L] points to information asymmetry between funds and outside investors resulting in mismatch between investment opportunities and capital that is not fully undone by the firm's actions [@bbl17]. This interpretation also provides a potential explanation for the observed relation between measures of activeness such as active share [@cp09] or industry concentration [@ksz05] and future fund performance: if managers have private information about investment opportunities, their actions carry information about expected returns.

@ps12 argue that each fund's investment opportunities become less lucrative as the size of competing funds increases. Decreasing returns to competitor scale are grounded in liquidity constraints and the associated price impact of other funds' trades. Consider a skilled fund receiving signals of the fundamental value of securities. In the absence of competitors, the limiting factor of the fund's profits is the price impact of its own trades. Introducing another fund that receives correlated signals is detrimental to the fund's profitability. Since both funds chase similar investments, either one might be first to invest in a particular opportunity, pushing up its price. The total impact of the other fund will depend on both the similarity of its signals, which determines the likelihood of being leapfrogged, and the fund's size, which governs the magnitude of price impact. Competitor size is therefore the sum of the product of similarity and fund size across all potential competitors:
$$
\text{Competitor Size}_i = \sum_{j\neq i} \text{Similarity}_{i,j} \times \text{Fund Size}_j.
$$
If funds receive identical signals, similarity equals one, and competitor size will equal aggregate industry size [@pst15].^[I measure fund similarity by the cosine similarity of market capitalization adjusted portfolio weights. I cap adjust portfolio weights by dividing them with market weights, as cross-holdings of small-capitalization stocks are more informative of similarity than cross-holdings of large capitalization stocks [@ccp05].] Unlike industry size, competitor size is specific to each fund, which allows for studying variation in the cross-section. Most importantly, taking fund similarity into account enables me to analyze novel evidence on decreasing returns to competitor scale from a natural experiment.

@bg04 posit a relation between active share and fund size and fees. @pst17L introduce a richer model of fund behavior, proposing that funds jointly optimize turnover and portfolio liquidity. Portfolio liquidity is a multi-dimensional object that can be decomposed as a product of stock liquidity and diversification (itself a product of coverage and balance). I make the model-driven argument that if investors do not fully recognize the detrimental impact of competition on future returns, then increases in competitor size will have a measurable impact on fund activeness even conditional on own size, fees, and time fixed effects.

My empirical analysis is based on a sample of actively managed U.S. equity funds spanning `r combined[, min(year(date))]`-`r combined[, max(year(date))]`, with size and returns information from CRSP linked to Thomson Reuters holdings data. Guided by theory, I relate quarterly changes in competitor scale to changes in active share, turnover to portfolio liquidity ratio, and various components of portfolio liquidity, conditional on own size, expense ratio, and time fixed effects. I find that funds react to increases in competitor scale by decreasing active share and increasing all dimensions of portfolio liquidity.

I bolster the causal link between competitor scale, fund behavior, and performance by providing novel evidence from a natural experiment created by the 2003 mutual fund scandal. In September 2003, the New York State Attorney General announced investigations into illegal trading practices at several prominent mutual fund families. As investigations gained momentum, evidence mounted that families had allowed favored clients to abuse ordinary investors by trading fund shares at stale prices [@zitzewitz06]. By October 2004, a total of twenty-five fund families were embroiled in the scandal [@hw05]. The involved families represented a considerable proportion of the industry, collectively managing over a fifth of assets prior to the scandal. Following the announcement of the investigations, investors abruptly began withdrawing capital from tainted families (Figure \@ref(fig:scandalFlows)).

I exploit post-scandal outflows at tainted funds as an exogenous shock to the competitor size of funds pursuing similar investment strategies. We would expect the favorable impact of lessened competitor scale to be greatest for the closest pre-scandal competitors of tainted funds. Under the hypothesis of decreasing returns to competitor scale, these funds experience a comparative improvement in their investment opportunities. Therefore, we would expect them to increase capital allocation to active strategies relative to less close competitors of tainted funds, and see relative improvements in performance. I take two different approaches to testing these hypotheses, both of which confirm decreasing returns to competitor scale and the associated fund response.

Since involved funds are directly affected by the scandal, I identify decreasing returns to competitor scale by comparing outcome paths at untainted funds. The first approach compares pre- and post-scandal outcomes as a function of pre-scandal exposure to competition from tainted   funds. I measure exposure by the fraction of competitor scale in August 2003 accounted for by prospective tainted families. The competitor size of high exposure funds decreased significantly more during the scandal. Consistent with comparatively improved investment opportunities, high exposure funds increased active share and decreased portfolio liquidity relative to low exposure funds, and experienced comparatively better performance. Statistical tests show no evidence of differential trends by scandal exposure in the pre-period.

The second approach links fund outcomes directly to abnormal outflows at tainted funds. I use a linear model to decompose post-scandal flows at involved funds between time variation common to all funds and abnormal flows attributable to scandal involvement. I show that untainted funds whose tainted competitors experienced greater abnormal outflows saw relative declines in competitor size, improvements in performance, and shifted to more active portfolio management. Variation in competitor size attributable purely to abnormal outflows is negatively related to both fund performance and activeness, providing direct quasi-experimental evidence of decreasing returns to competitor scale.

The picture which emerges from these analyses is one in which portfolio managers optimize investment behavior in real time as they respond to fluctuations in investment opportunities that are not immediately apparent to outside investors. Such a world seems sensible. It is unlikely that retail investors pay the same level of attention to market developments as professional portfolio managers. Fund managers make trading decisions based on their perception of investment opportunities on a daily basis. Since they have more short-term flexibility over trading than over fund expense ratios, it makes sense that their portfolio allocation decisions would serve as an important dimension of optimizing behavior. This interpretation is also consistent with recent evidence from the literature on fund optimizing behavior in the face of time-varying investment opportunities. @knv16 argue that mutual funds allocate attention optimally between factor timing and stock picking as the nature of opportunities varies over the business cycle. @pst17 present evidence that funds exploit improved investment opportunities by increasing turnover.

While the rise of "closet indexing" has received much attention and disapproval, scaling back active management ameliorates the pernicious effects of decreasing returns to scale, as it brings the costs of active trading closer in line with decreased benefits. Absent immediate outflows, deteriorating investment opportunities make a fund "too large." 
The fundamental issue might not so much be closet indexing, but imperfect flows causing mismatch between capital and investment opportunities.

The rest of the paper proceeds as follows.
Chapter \@ref(sec:litReview) reviews the related literature.
Chapter \@ref(sec:model) discusses the theoretical framework motivating the empirical analyses.
Chapter \@ref(sec:Data) describes the data and the construction of competitor size.
Chapter \@ref(sec:portfolio) presents an empirical analysis of capital allocation and competitor scale.
Chapter \@ref(sec:scandal) presents evidence from the natural experiment created by the 2003 mutual fund scandal.
Chapter \@ref(sec:conclusion) concludes.
The [Data Appendix](https://www.dropbox.com/s/qugvhb8b0wqp0cg/LJ_JMP_Data_Appendix.pdf?dl=0) describes in detail the steps in the construction of the dataset.
