\chapter{Summary Statistics} 
\label{sec:summaryStats}

```{r, include = FALSE}
# Setup ------------------------------------------------------------------------

# packages
pkgs <- c(
  "data.table",
  "zoo",
  "knitr",
  "ggplot2",
  "gridExtra",
  "xtable")
lapply(pkgs, library, character.only = TRUE)
options(knitr.kable.NA = '')

# set figures at top of page
knitr::opts_chunk$set(fig.pos = 'H')

# quiet xtable
options(xtable.comment = FALSE)

# custom colors
azure <- "#007FFF"
orangebrown <- "#E67300"
lgreen <- "#00eb76"

# table macros
mrn <- "\\midrule \\\\\n"
mr <- "\\midrule"
PHead <- function(nc, txt) {
  paste0("\\multicolumn{", nc, "}{c}{\\textbf{", txt, "}}\\\\\n")
}
TCap <- function(nc, tcap) {
  paste0("\\multicolumn{", nc, "}{p{.975\\textwidth}}{", tcap, "}", 
  "\\\\\n \\addlinespace")
}
px <- function(tab, ...) {
  print.xtable(tab,
    sanitize.text.function = function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.99\\textwidth",
    caption.placement = 'top',
	table.placement = "H",
	...)
}

setwd("..")

# load tables
tab.summary <- readRDS("tab/summary_stats.Rds")

# load figures
fig.summary <- readRDS("fig/summary_plots.Rds")
# ------------------------------------------------------------------------
```


```{r sumStats, , echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
# Summary Statistics -----------------------------------------------------------

# add caption and panel headers
rb <- nrow(tab.summary$summary.stats$sub.results$fund.level)
nc <- ncol(tab.summary$summary.stats$results)
# add caption and panel headers
add.to.row <- list(
  pos = list(-1, 0, 0, rb, rb, rb), 
  command = c(
    TCap(nc + 1, tab.summary$summary.stats$caption),
    mrn, PHead(nc + 1, "Panel A: Fund level means"),
    mrn, PHead(nc + 1, "Panel B: Fund-month level statistics"), mr))

# convert table to latex
out.tab <- px(xtable(tab.summary$summary.stats$results,
    caption = tab.summary$summary.stats$title,
    label = "tab:sumStats",
    display = c("s", "d", rep("f", (ncol(tab.summary$summary.stats$results) - 1)))
    ),
	print.results = FALSE,
    format.args = list(big.mark = ",", 
	drop0trailing = TRUE))
# fix alignment
out.tab <- gsub("rrrrrrrrrrr", "@{}lrYYYYYYYYY@{}", out.tab, fixed = TRUE)

# print table
cat(out.tab)
# ------------------------------------------------------------------------------
```


```{r correlations, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}
# Correlations -----------------------------------------------------------------

# add caption and panel headers
rb <- nrow(tab.summary$correlations$sub.results$unconditional)
nc <- ncol(tab.summary$correlations$results)
# add caption and panel headers
add.to.row <- list(
  pos = list(0, 0, 0, rb, rb, rb, rb), 
  command = c(
    mr, PHead(nc, ""), PHead(nc, "Panel A: Unconditional"),
    mr, PHead(nc, ""), PHead(nc, "Panel B: Within-fund correlations"), mr))

# convert table to latex
px(xtable(tab.summary$correlations$results,
  align = paste(c("ll|", rep("Z", (nc - 1))), collapse = ""),
  caption = tab.summary$correlations$title,
  label = "tab:correlations",
  display = c("s", rep("f", nc)),
  digits = 2))
# ------------------------------------------------------------------------------
```

```{r industrySize, echo=FALSE, dpi = 300, fig.width = 6, fig.height = 3, fig.align = 'center', fig.cap = paste(fig.summary$industry$title, fig.summary$industry$caption), fig.scap = fig.summary$industry$title}
# Industry Size Time Series Plot -----------------------------------------------

fig.summary$industry$results
# ------------------------------------------------------------------------------
```

