\chapter{Additional Results: Capital Allocation}

```{r, include = FALSE}
# Setup ------------------------------------------------------------------------

# packages
pkgs <- c(
  "data.table",
  "zoo",
  "knitr",
  "xtable"
)
lapply(pkgs, library, character.only = TRUE)
options(knitr.kable.NA = '')

# macros for labeling tables
TCap <- function(nc, txt) {
  paste0("\\multicolumn{", nc, "}{p{.975\\textwidth}}{", txt, "}",
    " \\\\\n \\addlinespace")
}
px <- function(tab, ...) {
  print.xtable(tab,
    sanitize.text.function=function(x){x},
    booktabs = TRUE,
    add.to.row = add.to.row,
    size = "\\scriptsize",
    tabular.environment = "tabularx",
    width="0.975\\textwidth",
    include.rownames=FALSE,
    caption.placement = 'top',
	table.placement="H",
	...)
}

# quiet xtable
options(xtable.comment = FALSE)

# directories
setwd("..")

# load tables
reg.behavior <- readRDS("tab/reg_behavior.Rds")
# ----------------------------------------------------------------------
```


```{r fundResponseMXBim, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'} 
# Capital Allocation, Benchmark X Time FE -----------------------------------------

# label columns
setnames(reg.behavior$bm$results, 
  c("Dep. Var.:", "$\\Delta\\ln(AS)$", "$\\Delta\\ln(TL^{-1/2})$",
    "$\\Delta\\ln(L)$", "$\\Delta\\ln(S)$", "$\\Delta\\ln(D)$", 
    "$\\Delta\\ln(C)$", "$\\Delta\\ln(B)$"))

# add caption to top of table
nc <- ncol(reg.behavior$bm$results)
add.to.row <- list(
  pos = list(-1), 
  command = TCap(nc, reg.behavior$bm$caption))

# print the table
px(xtable(reg.behavior$bm$results,
  align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
  caption = reg.behavior$bm$title,
  label = "tab:fundResponseMXBim"))
# --------------------------------------------------------------------------------
```


```{r fundResponse08, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'} 
# Capital Allocation, Pre-2008 ---------------------------------------------------

# label columns
setnames(reg.behavior$baseline.08$results, 
  c("Dep. Var.:", "$\\Delta\\ln(AS)$", "$\\Delta\\ln(TL^{-1/2})$",
    "$\\Delta\\ln(L)$", "$\\Delta\\ln(S)$", "$\\Delta\\ln(D)$", 
    "$\\Delta\\ln(C)$", "$\\Delta\\ln(B)$"))

# add caption to top of table
nc <- ncol(reg.behavior$baseline.08$results)
add.to.row <- list(
  pos = list(-1), 
  command = TCap(nc, reg.behavior$baseline.08$caption))

# print the table
px(xtable(reg.behavior$baseline.08$results,
  align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
  caption = reg.behavior$baseline.08$title,
  label = "tab:fundResponse08"))
# --------------------------------------------------------------------------------
```


```{r fundResponseMXBim08, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'} 
# Capital Allocation, Benchmark X Time FE Pre-2008 -------------------------------

# label columns
setnames(reg.behavior$bm.08$results, 
  c("Dep. Var.:", "$\\Delta\\ln(AS)$", "$\\Delta\\ln(TL^{-1/2})$",
    "$\\Delta\\ln(L)$", "$\\Delta\\ln(S)$", "$\\Delta\\ln(D)$", 
    "$\\Delta\\ln(C)$", "$\\Delta\\ln(B)$"))

# add caption to top of table
nc <- ncol(reg.behavior$bm.08$results)
add.to.row <- list(
  pos = list(-1), 
  command = TCap(nc, reg.behavior$bm$caption))

# print the table
px(xtable(reg.behavior$bm.08$results,
  align = paste(c("ll", rep("Y", (nc - 1))), collapse = ""),
  caption = reg.behavior$bm.08$title,
  label = "tab:fundResponseMXBim08"))
# --------------------------------------------------------------------------------
```
